#ifndef INTERFACEDEFS_HPP_
#define INTERFACEDEFS_HPP_

#include "dbusipc/dbusipc.h"

extern DBUSIPC_tConstStr DBUSIPC_INTERFACE_NAME;
extern DBUSIPC_tConstStr DBUSIPC_INTERFACE_SIGNAL_NAME;
extern DBUSIPC_tConstStr DBUSIPC_INTERFACE_METHOD_NAME;
extern DBUSIPC_tConstStr DBUSIPC_INTERFACE_ERROR_NAME;
extern const DBUSIPC_tChar DBUSIPC_INTERFACE_SIGNAL_SIGNATURE[];
extern DBUSIPC_tConstStr INTROSPECTION_INTERFACE_METHOD_NAME;

#endif /* Guard for INTERFACEDEFS_HPP_ */
